### ISSUE TITLE
support for different distributions

### ISSUE THREAD

**Issue by tpham3783** [edkit/edkit-agent#1]
I just want you to know that I've packaged edkit for Ubuntu, and thus far, the package only built successfully for Trusty, there are some problems encountered with other versions.

packaged edkit: https://code.launchpad.net/~tpham3783/+recipe/edkit-daily

here is the break down of the build problems for other flavors:

xenial & Willy:

libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../.. -D_GNU_SOURCE -DNO_SSL -I../../include/edkit/toolbox -I/usr/include/json-c -fPIC -g -O2 -fno-optimize-sibling-calls -fno-omit-frame-pointer -c Os/CallStack.cpp -o Os/libedkit_toolbox_la-CallStack.o >/dev/null 2>&1
/bin/bash ../../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../..  -D_GNU_SOURCE -DNO_SSL -I../../include/edkit/toolbox -I/usr/include/json-c  -fPIC -g -O2 -c -o Os/libedkit_toolbox_la-rtsym.lo `test -f 'Os/rtsym.c' || echo './'`Os/rtsym.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../.. -D_GNU_SOURCE -DNO_SSL -I../../include/edkit/toolbox -I/usr/include/json-c -fPIC -g -O2 -c Os/rtsym.c  -fPIC -DPIC -o Os/.libs/libedkit_toolbox_la-rtsym.o
In file included from Os/rtsym.c:35:0:
../../include/edkit/toolbox/rtsym.h:59:2: error: #error Unsupported ABI
 #error Unsupported ABI
  ^
Makefile:541: recipe for target 'Os/libedkit_toolbox_la-rtsym.lo' failed

vivid:

I do not know why it broke, but will update you if the problem is related to API.

thanks,

-Pham

**Comment by tpham3783** [comment]
Also, I plan to support cross build for ARM architecture soon.  thank you for your valuable work!

**Comment by MainRo** [comment]
For xenial & Willy, what is the version of gcc that is used, and what architecture (x86 or x86_64) ?

You should be able to cross-compile on arm without issues. I regularly use it on arm (32 bits), mips, and sh4.

**Comment by MainRo** [comment]
ok, I saw the infos in the build logs, xenial is x86-64, gcc 5.3.1-6. I will look at this. I wanted to remove these hardcoded mangled names since some time.

**Comment by tpham3783** [comment]
thanks,

i've used it on arm before... I just want to provide the compiled tool to
big audiences...

Other than the EBI error, i think it should build just fine for amd64.

**Comment by MainRo** [comment]
Commit c4fa40a1b5b4f9d67e3f387315ecf5a96610e18e should fix be issue

**Comment by tpham3783** [comment]
Thanks... I will check it out to test pretty soon

**Comment by tpham3783** [comment]
It builds on all target platforms now, except precise BC it does not have a
dependency..  Other than that... Great work!
